    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: setup Java 14
            uses: actions/setup-java@v1
            with:
                java-version: 14           
          - uses: education/autograding@v1
